# -*- generated by 1.0.14 -*-
import da
PatternExpr_232 = da.pat.TuplePattern([da.pat.ConstantPattern('Yo bro')])
PatternExpr_237 = da.pat.FreePattern('source')
_config_object = {}

class Client(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_0', PatternExpr_232, sources=[PatternExpr_237], destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_231])])

    def setup(self, clientID, requests, clientTimeout, replicaInfos, private_key, **rest_264):
        super().setup(clientID=clientID, requests=requests, clientTimeout=clientTimeout, replicaInfos=replicaInfos, private_key=private_key, **rest_264)
        self._state.clientID = clientID
        self._state.requests = requests
        self._state.clientTimeout = clientTimeout
        self._state.replicaInfos = replicaInfos
        self._state.private_key = private_key
        self._state.pID = self._state.clientID
        self._state.nReq = self._state.requests
        self._state.timeout = self._state.clientTimeout
        self._state.replicaInfos = self._state.replicaInfos
        self._state.private_key = self._state.private_key

    def run(self):
        self.output('Yo running client!!!')
        self.output('Broadcasting messages to replicas')
        for (_, replicaInfo) in self._state.replicaInfos.items():
            self.send(('request', 'abcd'), to=replicaInfo.process)
        super()._label('_st_label_223', block=False)
        _st_label_223 = 0
        while (_st_label_223 == 0):
            _st_label_223 += 1
            if (self._state.nReq == 0):
                _st_label_223 += 1
            else:
                super()._label('_st_label_223', block=True)
                _st_label_223 -= 1

    def _Client_handler_231(self, source):
        if (source in self._state.replicaInfos):
            replicaInfo = self._state.replicaInfos[source]
            self.output('Got message from replica ', replicaInfo.replicaID)
            self._state.nReq -= 1
        else:
            self.output('Received unknown message')
    _Client_handler_231._labels = None
    _Client_handler_231._notlabels = None
