# -*- generated by 1.0.14 -*-
import da
_config_object = {}
from Pacemaker import Pacemaker as PM

def run():
    self.output('Running for first time')

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        self.output('hello')
        p = PM.Pacemaker(None, None, None)
        p.start_timer(0)
